name = "UnitfulMoles"
uuid = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"
authors = ["Rafael Schouten", "Benoit Pasquier"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
